#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Install contract on all members peers in channel
  include_tasks: install-contract-member.yml
  when: member.endorsing_peers is defined
  with_items: "{{ definition.endorsing_members }}"
  loop_control:
      loop_var: member