#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Get the list of components
  uri:
    url: "{{ infrastructure.software.api_endpoint }}/ak/api/v1/components?skip_cache=yes"
    url_username: "{{ infrastructure.software.api_key }}"
    url_password: "{{ infrastructure.software.api_secret }}"
    method: GET
    return_content: yes
    validate_certs: no
  register: ibp_components

- name: Check for MSP
  set_fact:
    ibp_msp_count: "{{
      ibp_components.json |
      selectattr('display_name', 'defined') |
      selectattr('display_name', 'eq', organization.msp.ibp.display_name) |
      list
    }}"

- name: Delete MSP
  uri:
    url: "{{ infrastructure.software.api_endpoint }}/ak/api/v1/components/{{ ibp_msp.id }}"
    url_username: "{{ infrastructure.software.api_key }}"
    url_password: "{{ infrastructure.software.api_secret }}"
    method: DELETE
    validate_certs: no
  changed_when: True
  with_items: "{{ ibp_msp_count }}"
  loop_control:
    loop_var: ibp_msp