#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer1.importerorg.trade.com:

networks:
  trade:

services:
  couchdb-peer1.importerorg.trade.com:
    container_name: couchdb-peer1.importerorg.trade.com
    image: couchdb:2.3
    platform: $PLATFORM
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      - trade

  peer1.importerorg.trade.com:
    container_name: peer1.importerorg.trade.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.importerorg.trade.com
      - CORE_PEER_ADDRESS=peer1.importerorg.trade.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer1.importerorg.trade.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.importerorg.trade.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.importerorg.trade.com:11051
      - CORE_PEER_LOCALMSPID=ImporterOrgMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-peer1.importerorg.trade.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb-peer1.importerorg.trade.com
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/importerorg.trade.com/peers/peer1.importerorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/importerorg.trade.com/peers/peer1.importerorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer1.importerorg.trade.com:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - trade
